### ISSUE TITLE
SEP7 Stellar URI should support "seqNum" replace param.

### ISSUE THREAD

**Issue by pselden** [keybase/stellarnet#85]
Currently when using replacements in SEP7 Stellar URIs, it appears that Keybase has the ability to replace source accounts in transactions. However, that is not very useful if it does not also replace the sequence number. Unfortunately adding the "seqNum" replace param results in a "Sorry you cannot use this replace param" error.

Here is how I tested this:

1. Created a Stellar URI sending 0.01 XLM to my own account, with a different source account, and the sequence number of that source account. This Stellar URI specifies that `sourceAccount` should be replaced.

 [web+stellar:tx?xdr=AAAAAO6JQTfmXnAUTbjZ%2FQ6kMiwYQK96tab9CrOkRDhgleCvAAAAZAEpCUIAAAAEAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAARQ8lgldVTeCUV%2BoysRUOl0J13Iuxv%2Fa1l%2FDuWahtdwwAAAAAAAAAAAABhqAAAAAAAAAAAA%3D%3D&origin_domain=test.stellarguard.me&replace=sourceAccount%3ASRC%3BSRC%3Athe+source+account&signature=hYKXcxDPESUHdbJP9aCWMTnYNP0MUJsRnddWRQ1H15r8%2BUS86V5LRQo3yi4Ft771ClRphv8Q%2BbiA8sZ1xyVkCQ%3D%3D](web+stellar:tx?xdr=AAAAAO6JQTfmXnAUTbjZ%2FQ6kMiwYQK96tab9CrOkRDhgleCvAAAAZAEpCUIAAAAEAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAARQ8lgldVTeCUV%2BoysRUOl0J13Iuxv%2Fa1l%2FDuWahtdwwAAAAAAAAAAAABhqAAAAAAAAAAAA%3D%3D&origin_domain=test.stellarguard.me&replace=sourceAccount%3ASRC%3BSRC%3Athe+source+account&signature=hYKXcxDPESUHdbJP9aCWMTnYNP0MUJsRnddWRQ1H15r8%2BUS86V5LRQo3yi4Ft771ClRphv8Q%2BbiA8sZ1xyVkCQ%3D%3D)

2. When trying to submit this, I get a "Stellar network error" message.

3. Created a Stellar URI that was the same as before, but used the correct sequence number for my own account (still used the other account's source account).

[web+stellar:tx?xdr=AAAAAO6JQTfmXnAUTbjZ%2FQ6kMiwYQK96tab9CrOkRDhgleCvAAAAZAFAdlYAAAAcAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAARQ8lgldVTeCUV%2BoysRUOl0J13Iuxv%2Fa1l%2FDuWahtdwwAAAAAAAAAAAABhqAAAAAAAAAAAA%3D%3D&origin_domain=test.stellarguard.me&replace=sourceAccount%3ASRC%3BSRC%3Athe+source+account&signature=gbcazRsdRuJi2A085kkK8R%2F66LPaV%2B%2FTaFpaiG%2F%2FdfDPtFTJxn2Nd2xO6Ssxjpy3esOr3lr3eUe5tCWOQ%2FkNDA%3D%3D](web+stellar:tx?xdr=AAAAAO6JQTfmXnAUTbjZ%2FQ6kMiwYQK96tab9CrOkRDhgleCvAAAAZAFAdlYAAAAcAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAARQ8lgldVTeCUV%2BoysRUOl0J13Iuxv%2Fa1l%2FDuWahtdwwAAAAAAAAAAAABhqAAAAAAAAAAAA%3D%3D&origin_domain=test.stellarguard.me&replace=sourceAccount%3ASRC%3BSRC%3Athe+source+account&signature=gbcazRsdRuJi2A085kkK8R%2F66LPaV%2B%2FTaFpaiG%2F%2FdfDPtFTJxn2Nd2xO6Ssxjpy3esOr3lr3eUe5tCWOQ%2FkNDA%3D%3D)

4. Clicking this succeeded, indicating that it replaced the source account, but left the sequence number.

----

Presently, it appears that source account replacements are kind of worthless since you have to have set the correct sequence number ahead of time. Supporting the `seqNum` replacement param would alleviate this and make this so much more useful.

----

Note: I have a playground for Stellar URIs that you can try here (to make the link clickable at least): https://stellarguard.github.io/stellar-uri/demo

**Comment by pselden** [comment]
Hey @patrickxb -- since it looks like you added the original support for sourceAccount replacement, just putting this on your radar.

Thanks!

**Comment by patrickxb** [comment]
The sequence number replacement is handled in keybase/client.

**Comment by pselden** [comment]
It's handled there (with 0) -- but it doesn't support "seqNum" replace param that also can indicate that it should be replaced.

There was also discussion here: https://github.com/stellar/stellar-protocol/pull/441#issuecomment-558580701 by @nikhilsaraf that eventually 0 might be deprecated (but... now that it's in use, doesn't seem like it can... doh).

What i'm suggesting is that you add something similar to what you did with "tx.sourceAccount" and flag it as needing to be replaced (you could keep the logic here and check for === 0 or tx.seqNum is present.

Currently if I create a (presumably valid) sep7 link with "seqNum" replacement, then it rejects it saying it doesn't support that.

**Comment by patrickxb** [comment]
Why would a sequence number other than zero ever be in a sep7 tx link?  

If it's not there at all, then the unmarshaling of the xdr will be zero by default, so specifying a replace of seqNum seems redundant.

**Comment by pselden** [comment]
It likely won't be 0 (although it could be anything) -- it's just that with SEP-10, sequence number of 0 is a valid transaction to be signed, so we wouldn't actually do replacements on it. Thus specifying it explicitly would be required.
